# Generated by Django 2.2.9 on 2020-01-28 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200128_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='study_year',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
